cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
 
  resources :cats
  
end

cats_99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_99/app/models/cat.rb
require "action_view"

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    COLORS = ["Red", "Yellow", "Black", "White", "Gray"]
    SEXES = ["M", "F"]
    validates :name, :birth_date, presence: true
    validates :color, inclusion: COLORS
    validates :sex, inclusion: SEXES

    def age
        time_ago_in_words(birth_date)
    end


end

cats_99/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord

    

end

cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController



    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])
        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            flash.now[:errors] = @cat.errors.full_messages
            render :edit
        end
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end

    end



    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end
end

cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_99/app/views/cats/_form.html.erb
<h1><%= edit ? 'Edit Your Cat Here' : 'Create A New Cat Here'%></h1>

<% if edit %>
    <%action = cat_url(cat)%>
    <%method = 'patch'%>
<% else %>
    <%action = cats_url(cat)%>
    <%method = 'post'%>
<% end%>


<form action="<%= action %>" method="post">
    <input type="hidden" name="_method" value=<%=method%>>

<label for="cat_name">Cat Name: </label>
<input type="text" name="cat[name]" id="cat_name" value="<%= cat.name %>">

<div id="sex_options">
<label for="sex_options"> Sex: </label>
    
    <input type="radio" id="sex_choice"
     name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
    <label for="sex_choice">Male</label>

    <input type="radio" id="sex_choice2"
     name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %> >
    <label for="sex_choice2">Female</label>

</div>

<label for="cat_color">Cat Color: </label>
<select id="cat_color" name="cat[color]">
   <option disabled selected> -- Select a Color --</option>
    <% Cat::COLORS.each do |color| %>
        <option 
        <%= cat.color == color ? 'selected' :  "" %>
        value="<%=color%>"><%=color%></option>
    <% end%>
</select>

<label for="cat_birth_date">Cat Birthday: </label>
<input type="date" name="cat[birth_date]" id="cat_bith_date" value="<%=cat.birth_date%>">


<label for="cat_description"> Description:  </label>
<textarea name="cat[description]" id="cat_description"><%= cat.description %></textarea>

<input type="submit" value="<%= edit ? 'Edit Cat' : 'Create Cat'%>">

</form>

cats_99/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, edit: true %>

cats_99/app/views/cats/index.html.erb
<h1>All Cats</h1>

<ul>
    <% @cats.each do |cat| %>
        <li><%= cat.name %></li>
        <a href="<%= cat_url(cat) %>"><%= cat.name %>'s Profile</a>
    <% end %>
</ul>

cats_99/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, edit: false %>

cats_99/app/views/cats/show.html.erb
<h1><%= @cat.name %>'s Profile</h1>

<table>
    <tr>
        <th colspan="2"> <% @cat.name%> </th>
    </tr>
    <tr>
        <th> Attribute </th>
        <th> Value </th>
    </tr>
    <tr>
        <td> Name: </td>
        <td> <%=@cat.name%> </td>
    </tr>
    <tr>
        <td> Birth Day: </td>
        <td> <%=@cat.birth_date%> </td>
    </tr>
    <tr>
        <td> Color: </td>
        <td> <%=@cat.color%> </td>
    </tr>
    <tr>
        <td> Description: </td>
        <td> <%=@cat.description%> </td>
    </tr>
    <tr>
        <td> Sex: </td>
        <td> <%=@cat.sex%> </td>
    </tr>

</table>

cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>